### ISSUE TITLE
Source code issues

### ISSUE THREAD

**Issue by git0929** [BlueCat-de/SDM#3]
Hello, what is going on with this question, I will be very grateful for you to answer this question to me

SDM) hou@hou-System:~/SDM/Scripts$ python main_NSG.py --r_adv stackelberg3 --r_ego stackelberg --is_save True --save_model True --pretrain_ego True --adv_policy sumo --num_agents 5
  0%|                                                         | 0/100 [00:00<?, ?it/s] Retrying in 1 seconds
100%|██████████████████████████████████████████████| 200/200 [00:00<00:00, 208.67it/s]
 Retrying in 1 seconds███████████████████████████▍ | 193/200 [00:00<00:00, 281.79it/s]
  0%|                                                         | 0/100 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/hou/SDM/Scripts/main_NSG.py", line 440, in <module>
    absl.app.run(main)
  File "/home/hou/anaconda3/envs/SDM/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/hou/anaconda3/envs/SDM/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/hou/SDM/Scripts/main_NSG.py", line 326, in main
    eval(metrics, eval_ego_policy, FLAGS.adv_policy, trajs)
TypeError: eval expected at most 3 arguments, got 4

**Comment by BlueCat-de** [comment]
Thanks for pointing this out. I fixed this issue in the latest push [update eval](https://github.com/BlueCat-de/SDM/commit/cd7f5c94a2e5f25cc259f8f8c6c135bbb44a4c4a).
